name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y clang-format clang-tidy libcmocka-dev

      - name: Build
        run: ./scripts/build.sh
        
      - name: Check Code Formatting
        run: ./scripts/check_format.sh 

      - name: Run Static Analysis
        run: ./scripts/run_clang_tidy.sh

      - name: Test
        run: ./scripts/test.sh
