name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y clang-format clang-tidy libcmocka-dev

      - name: Build
        run: ./scripts/build.sh
        
      - name: Check Code Formatting
        run: |
          find . -type f \( -name "*.c" -o -name "*.h" \) -not \( -path "./src/stb_image/*" -o -path "./build/*" \) | \
          xargs -n1 sh -c 'clang-format --dry-run --Werror "$1" || { echo "Formatting error in $1"; exit 1; }' _
        shell: bash

      - name: Run Static Analysis
        run: |
          find . -type f -name "*.c" -not \( -path "./tests/*" -o -path "./build/*" \) | xargs clang-tidy -p ./build
        shell: bash

      - name: Test
        run: ./scripts/test.sh